server: 
  port: 55666

spring: 
  activemq:
    broker-url: tcp://192.168.47.129:61616 #MQ服務器地址
    user: admin
    password: admin
    packages:
      trust-all: true #傳遞物件需要打開他

      
  jms: 
    pub-sub-domain: true # false = Queue(默認)，true = Topic


