server: 
  port: 8083

spring: 
  activemq:
    #broker-url: tcp://192.168.47.129:61616 #MQ服務器地址
    broker-url: nio://192.168.47.129:61618 #MQ服務器地址
    user: admin
    password: admin
    packages:
      trust-all: true #傳遞物件需要打開他
      #trusted:
     # - com.frank.activemq.dto.Message

      
  jms: 
    pub-sub-domain: false # false = Queue(默認)，true = Topic


